package com.example.chivas.dbres.db.greendao.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.chivas.dbres.db.greendao.entity.BillDes;
import com.example.chivas.dbres.db.greendao.entity.SimpleEntity;
import com.example.chivas.dbres.db.greendao.entity.SimpleIndexedEntity;
import com.example.chivas.dbres.db.greendao.entity.WaybillInfo;

import com.example.chivas.dbres.db.greendao.entity.BillDesDao;
import com.example.chivas.dbres.db.greendao.entity.SimpleEntityDao;
import com.example.chivas.dbres.db.greendao.entity.SimpleIndexedEntityDao;
import com.example.chivas.dbres.db.greendao.entity.WaybillInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billDesDaoConfig;
    private final DaoConfig simpleEntityDaoConfig;
    private final DaoConfig simpleIndexedEntityDaoConfig;
    private final DaoConfig waybillInfoDaoConfig;

    private final BillDesDao billDesDao;
    private final SimpleEntityDao simpleEntityDao;
    private final SimpleIndexedEntityDao simpleIndexedEntityDao;
    private final WaybillInfoDao waybillInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billDesDaoConfig = daoConfigMap.get(BillDesDao.class).clone();
        billDesDaoConfig.initIdentityScope(type);

        simpleEntityDaoConfig = daoConfigMap.get(SimpleEntityDao.class).clone();
        simpleEntityDaoConfig.initIdentityScope(type);

        simpleIndexedEntityDaoConfig = daoConfigMap.get(SimpleIndexedEntityDao.class).clone();
        simpleIndexedEntityDaoConfig.initIdentityScope(type);

        waybillInfoDaoConfig = daoConfigMap.get(WaybillInfoDao.class).clone();
        waybillInfoDaoConfig.initIdentityScope(type);

        billDesDao = new BillDesDao(billDesDaoConfig, this);
        simpleEntityDao = new SimpleEntityDao(simpleEntityDaoConfig, this);
        simpleIndexedEntityDao = new SimpleIndexedEntityDao(simpleIndexedEntityDaoConfig, this);
        waybillInfoDao = new WaybillInfoDao(waybillInfoDaoConfig, this);

        registerDao(BillDes.class, billDesDao);
        registerDao(SimpleEntity.class, simpleEntityDao);
        registerDao(SimpleIndexedEntity.class, simpleIndexedEntityDao);
        registerDao(WaybillInfo.class, waybillInfoDao);
    }
    
    public void clear() {
        billDesDaoConfig.clearIdentityScope();
        simpleEntityDaoConfig.clearIdentityScope();
        simpleIndexedEntityDaoConfig.clearIdentityScope();
        waybillInfoDaoConfig.clearIdentityScope();
    }

    public BillDesDao getBillDesDao() {
        return billDesDao;
    }

    public SimpleEntityDao getSimpleEntityDao() {
        return simpleEntityDao;
    }

    public SimpleIndexedEntityDao getSimpleIndexedEntityDao() {
        return simpleIndexedEntityDao;
    }

    public WaybillInfoDao getWaybillInfoDao() {
        return waybillInfoDao;
    }

}
