package com.example.chivas.dbres.db.objectbox.entity;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "BillDes".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class BillDesCursor extends Cursor<BillDes> {
    @Internal
    static final class Factory implements CursorFactory<BillDes> {
        @Override
        public Cursor<BillDes> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new BillDesCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final BillDes_.BillDesIdGetter ID_GETTER = BillDes_.__ID_GETTER;


    private final static int __ID_billNo = BillDes_.billNo.id;
    private final static int __ID_des = BillDes_.des.id;

    public BillDesCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, BillDes_.__INSTANCE, boxStore);
    }

    @Override
    public final long getId(BillDes entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @Override
    public final long put(BillDes entity) {
        String billNo = entity.billNo;
        int __id1 = billNo != null ? __ID_billNo : 0;
        String des = entity.des;
        int __id2 = des != null ? __ID_des : 0;

        long __assignedId = collect313311(cursor, entity._id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, billNo, __id2, des,
                0, null, 0, null,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity._id = __assignedId;

        return __assignedId;
    }

}
