
package com.example.chivas.dbres.db.objectbox.entity;

import com.example.chivas.dbres.db.objectbox.entity.SimpleEntityCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "SimpleEntity". Can be used for QueryBuilder and for referencing DB names.
 */
public final class SimpleEntity_ implements EntityInfo<SimpleEntity> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "SimpleEntity";

    public static final int __ENTITY_ID = 2;

    public static final Class<SimpleEntity> __ENTITY_CLASS = SimpleEntity.class;

    public static final String __DB_NAME = "SimpleEntity";

    public static final CursorFactory<SimpleEntity> __CURSOR_FACTORY = new Factory();

    @Internal
    static final SimpleEntityIdGetter __ID_GETTER = new SimpleEntityIdGetter();

    public final static SimpleEntity_ __INSTANCE = new SimpleEntity_();

    public final static io.objectbox.Property<SimpleEntity> _id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "_id", true, "_id");

    public final static io.objectbox.Property<SimpleEntity> simpleBoolean =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, boolean.class, "simpleBoolean");

    public final static io.objectbox.Property<SimpleEntity> simpleByte =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, byte.class, "simpleByte");

    public final static io.objectbox.Property<SimpleEntity> simpleShort =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, short.class, "simpleShort");

    public final static io.objectbox.Property<SimpleEntity> simpleInt =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, int.class, "simpleInt");

    public final static io.objectbox.Property<SimpleEntity> simpleLong =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, long.class, "simpleLong");

    public final static io.objectbox.Property<SimpleEntity> simpleFloat =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, float.class, "simpleFloat");

    public final static io.objectbox.Property<SimpleEntity> simpleDouble =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, double.class, "simpleDouble");

    public final static io.objectbox.Property<SimpleEntity> simpleString =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, String.class, "simpleString");

    public final static io.objectbox.Property<SimpleEntity> simpleByteArray =
        new io.objectbox.Property<>(__INSTANCE, 9, 10, byte[].class, "simpleByteArray");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<SimpleEntity>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        _id,
        simpleBoolean,
        simpleByte,
        simpleShort,
        simpleInt,
        simpleLong,
        simpleFloat,
        simpleDouble,
        simpleString,
        simpleByteArray
    };

    public final static io.objectbox.Property<SimpleEntity> __ID_PROPERTY = _id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<SimpleEntity> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<SimpleEntity>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<SimpleEntity> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<SimpleEntity> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<SimpleEntity> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class SimpleEntityIdGetter implements IdGetter<SimpleEntity> {
        @Override
        public long getId(SimpleEntity object) {
            return object._id;
        }
    }

}
