package com.example.chivas.dbres.db.objectbox.entity;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "SimpleEntity".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class SimpleEntityCursor extends Cursor<SimpleEntity> {
    @Internal
    static final class Factory implements CursorFactory<SimpleEntity> {
        @Override
        public Cursor<SimpleEntity> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new SimpleEntityCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final SimpleEntity_.SimpleEntityIdGetter ID_GETTER = SimpleEntity_.__ID_GETTER;


    private final static int __ID_simpleBoolean = SimpleEntity_.simpleBoolean.id;
    private final static int __ID_simpleByte = SimpleEntity_.simpleByte.id;
    private final static int __ID_simpleShort = SimpleEntity_.simpleShort.id;
    private final static int __ID_simpleInt = SimpleEntity_.simpleInt.id;
    private final static int __ID_simpleLong = SimpleEntity_.simpleLong.id;
    private final static int __ID_simpleFloat = SimpleEntity_.simpleFloat.id;
    private final static int __ID_simpleDouble = SimpleEntity_.simpleDouble.id;
    private final static int __ID_simpleString = SimpleEntity_.simpleString.id;
    private final static int __ID_simpleByteArray = SimpleEntity_.simpleByteArray.id;

    public SimpleEntityCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, SimpleEntity_.__INSTANCE, boxStore);
    }

    @Override
    public final long getId(SimpleEntity entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @Override
    public final long put(SimpleEntity entity) {
        String simpleString = entity.simpleString;
        int __id8 = simpleString != null ? __ID_simpleString : 0;
        byte[] simpleByteArray = entity.simpleByteArray;
        int __id9 = simpleByteArray != null ? __ID_simpleByteArray : 0;

        long __assignedId = collect313311(cursor, entity._id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id8, simpleString, 0, null,
                0, null, __id9, simpleByteArray,
                __ID_simpleLong, entity.simpleLong, __ID_simpleInt, entity.simpleInt,
                __ID_simpleShort, entity.simpleShort, __ID_simpleByte, entity.simpleByte,
                __ID_simpleBoolean, entity.simpleBoolean ? 1 : 0, 0, 0,
                __ID_simpleFloat, entity.simpleFloat, __ID_simpleDouble, entity.simpleDouble);

        entity._id = __assignedId;

        return __assignedId;
    }

}
