
package com.example.chivas.dbres.db.objectbox.entity;

import com.example.chivas.dbres.db.objectbox.entity.WaybillInfoCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "WaybillInfo". Can be used for QueryBuilder and for referencing DB names.
 */
public final class WaybillInfo_ implements EntityInfo<WaybillInfo> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "WaybillInfo";

    public static final int __ENTITY_ID = 4;

    public static final Class<WaybillInfo> __ENTITY_CLASS = WaybillInfo.class;

    public static final String __DB_NAME = "WaybillInfo";

    public static final CursorFactory<WaybillInfo> __CURSOR_FACTORY = new Factory();

    @Internal
    static final WaybillInfoIdGetter __ID_GETTER = new WaybillInfoIdGetter();

    public final static WaybillInfo_ __INSTANCE = new WaybillInfo_();

    public final static io.objectbox.Property<WaybillInfo> _id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "_id", true, "_id");

    public final static io.objectbox.Property<WaybillInfo> goodsNo =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "goodsNo");

    public final static io.objectbox.Property<WaybillInfo> goodsType =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "goodsType");

    public final static io.objectbox.Property<WaybillInfo> containerNo =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "containerNo");

    public final static io.objectbox.Property<WaybillInfo> carLogoNo =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "carLogoNo");

    public final static io.objectbox.Property<WaybillInfo> transitDepotNo =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "transitDepotNo");

    public final static io.objectbox.Property<WaybillInfo> postNo =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, String.class, "postNo");

    public final static io.objectbox.Property<WaybillInfo> stationNo =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, String.class, "stationNo");

    public final static io.objectbox.Property<WaybillInfo> operatorNo =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, String.class, "operatorNo");

    public final static io.objectbox.Property<WaybillInfo> opTime =
        new io.objectbox.Property<>(__INSTANCE, 9, 10, Long.class, "opTime");

    public final static io.objectbox.Property<WaybillInfo> uploadFlag =
        new io.objectbox.Property<>(__INSTANCE, 10, 11, String.class, "uploadFlag");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<WaybillInfo>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        _id,
        goodsNo,
        goodsType,
        containerNo,
        carLogoNo,
        transitDepotNo,
        postNo,
        stationNo,
        operatorNo,
        opTime,
        uploadFlag
    };

    public final static io.objectbox.Property<WaybillInfo> __ID_PROPERTY = _id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<WaybillInfo> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<WaybillInfo>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<WaybillInfo> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<WaybillInfo> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<WaybillInfo> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class WaybillInfoIdGetter implements IdGetter<WaybillInfo> {
        @Override
        public long getId(WaybillInfo object) {
            return object._id;
        }
    }

}
