package com.example.chivas.dbres.db.objectbox.entity;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "WaybillInfo".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class WaybillInfoCursor extends Cursor<WaybillInfo> {
    @Internal
    static final class Factory implements CursorFactory<WaybillInfo> {
        @Override
        public Cursor<WaybillInfo> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new WaybillInfoCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final WaybillInfo_.WaybillInfoIdGetter ID_GETTER = WaybillInfo_.__ID_GETTER;


    private final static int __ID_goodsNo = WaybillInfo_.goodsNo.id;
    private final static int __ID_goodsType = WaybillInfo_.goodsType.id;
    private final static int __ID_containerNo = WaybillInfo_.containerNo.id;
    private final static int __ID_carLogoNo = WaybillInfo_.carLogoNo.id;
    private final static int __ID_transitDepotNo = WaybillInfo_.transitDepotNo.id;
    private final static int __ID_postNo = WaybillInfo_.postNo.id;
    private final static int __ID_stationNo = WaybillInfo_.stationNo.id;
    private final static int __ID_operatorNo = WaybillInfo_.operatorNo.id;
    private final static int __ID_opTime = WaybillInfo_.opTime.id;
    private final static int __ID_uploadFlag = WaybillInfo_.uploadFlag.id;

    public WaybillInfoCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, WaybillInfo_.__INSTANCE, boxStore);
    }

    @Override
    public final long getId(WaybillInfo entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @Override
    public final long put(WaybillInfo entity) {
        String goodsNo = entity.goodsNo;
        int __id1 = goodsNo != null ? __ID_goodsNo : 0;
        String goodsType = entity.goodsType;
        int __id2 = goodsType != null ? __ID_goodsType : 0;
        String containerNo = entity.containerNo;
        int __id3 = containerNo != null ? __ID_containerNo : 0;
        String carLogoNo = entity.carLogoNo;
        int __id4 = carLogoNo != null ? __ID_carLogoNo : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, goodsNo, __id2, goodsType,
                __id3, containerNo, __id4, carLogoNo);

        String transitDepotNo = entity.transitDepotNo;
        int __id5 = transitDepotNo != null ? __ID_transitDepotNo : 0;
        String postNo = entity.postNo;
        int __id6 = postNo != null ? __ID_postNo : 0;
        String stationNo = entity.stationNo;
        int __id7 = stationNo != null ? __ID_stationNo : 0;
        String operatorNo = entity.operatorNo;
        int __id8 = operatorNo != null ? __ID_operatorNo : 0;

        collect400000(cursor, 0, 0,
                __id5, transitDepotNo, __id6, postNo,
                __id7, stationNo, __id8, operatorNo);

        String uploadFlag = entity.uploadFlag;
        int __id10 = uploadFlag != null ? __ID_uploadFlag : 0;
        Long opTime = entity.opTime;
        int __id9 = opTime != null ? __ID_opTime : 0;

        long __assignedId = collect313311(cursor, entity._id, PUT_FLAG_COMPLETE,
                __id10, uploadFlag, 0, null,
                0, null, 0, null,
                __id9, __id9 != 0 ? opTime : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity._id = __assignedId;

        return __assignedId;
    }

}
